config/routes.rb
Rails.application.routes.draw do
  resources :tracks
  resources :tracks
  resources :tracks
  resources :cds

end

app/models/cd.rb
class Cd < ActiveRecord::Base
	has_many:track
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to:cd
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cds_controller.rb
class CdsController < ApplicationController
  before_action :set_cd, only: [:show, :edit, :update, :destroy]

  # GET /cds
  # GET /cds.json
  def index
    @cds = Cd.all
  end

  # GET /cds/1
  # GET /cds/1.json
  def show
  end

  # GET /cds/new
  def new
    @cd = Cd.new
  end

  # GET /cds/1/edit
  def edit
  end

  # POST /cds
  # POST /cds.json
  def create
    @cd = Cd.new(cd_params)

    respond_to do |format|
      if @cd.save
        format.html { redirect_to @cd, notice: 'Cd was successfully created.' }
        format.json { render :show, status: :created, location: @cd }
      else
        format.html { render :new }
        format.json { render json: @cd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cds/1
  # PATCH/PUT /cds/1.json
  def update
    respond_to do |format|
      if @cd.update(cd_params)
        format.html { redirect_to @cd, notice: 'Cd was successfully updated.' }
        format.json { render :show, status: :ok, location: @cd }
      else
        format.html { render :edit }
        format.json { render json: @cd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cds/1
  # DELETE /cds/1.json
  def destroy
    @cd.destroy
    respond_to do |format|
      format.html { redirect_to cds_url, notice: 'Cd was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cd
      @cd = Cd.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cd_params
      params.require(:cd).permit(:name, :artist, :genre)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :cd_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cds_helper.rb
module CdsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/cds/_form.html.erb
<%= form_for(@cd) do |f| %>
  <% if @cd.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cd.errors.count, "error") %> prohibited this cd from being saved:</h2>

      <ul>
      <% @cd.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cds/edit.html.erb
<h1>Editing Cd</h1>

<%= render 'form' %>

<%= link_to 'Show', @cd %> |
<%= link_to 'Back', cds_path %>

app/views/cds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Genre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cds.each do |cd| %>
      <tr>
        <td><%= cd.name %></td>
        <td><%= cd.artist %></td>
        <td><%= cd.genre %></td>
        <td><%= link_to 'Show', cd %></td>
        <td><%= link_to 'Edit', edit_cd_path(cd) %></td>
        <td><%= link_to 'Destroy', cd, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cd', new_cd_path %>
<%= link_to 'View tracks', tracks_path %>

app/views/cds/new.html.erb
<h1>New Cd</h1>

<%= render 'form' %>

<%= link_to 'Back', cds_path %>

app/views/cds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cd.name %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @cd.artist %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @cd.genre %>
</p>

<%= link_to 'Edit', edit_cd_path(@cd) %> |
<%= link_to 'Back', cds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :cd_id %><br>
    <%= select("track","cd_id", Cd.all.map{|c| [c.name, c.id]}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing Track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tracks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Cd</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tracks.each do |track| %>
      <tr>
        <td><%= track.name %></td>
        <td><%= track.cd_id %></td>
        <td><%= link_to 'Show', track %></td>
        <td><%= link_to 'Edit', edit_track_path(track) %></td>
        <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track', new_track_path %>
<%= link_to 'View Cd', cds_path %>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @track.name %>
</p>

<p>
  <strong>Cd:</strong>
  <%= @track.cd_id %>
</p>

<p>
	<strong>desc:</strong>
	
</p>

<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>